name: Create Post

on:
  issues:
    types: [opened]

jobs:
  test:
    if: startsWith(github.event.issue.title, 'post:')
    runs-on: ubuntu-latest

    steps:
      - name: Show issue information
        run: |
          echo "New post detected!"
          echo "Title: ${{ github.event.issue.title }}"
          echo "Body:"
          echo "${{ github.event.issue.body }}"